### ISSUE TITLE
Not an issue, a tip

### ISSUE THREAD

**Issue by vaisd007302** [swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI#66]
If you add the bookmarklet (gui.min.js) on mobile, all the hacks work correctly.

**Comment by Insanityyz** [comment]
Thanks for the information, @vaisd007302  ℹ️

Will be added to instructions on July 20th.

**Comment by Insanityyz** [comment]
Along with your name btw!

**Comment by swagging-post** [comment]
Bro @Insanityyz what? You don't even collab with me?

**Comment by swagging-post** [comment]
But I would've said that, sorry @vaisd007302

**Comment by vaisd007302** [comment]
No problem thanks,
