### ISSUE TITLE
How to use this on mobile?

### ISSUE THREAD

**Issue by Aleejoh13wpepperysalt** [swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI#73]

**Comment by vaisd007302** [comment]
Add the [gui.min.js](https://github.com/swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI/blob/main/cheats/gui/gui.min.js) to your mobile bookmarks. Then run it while you are on Blooket.

**Comment by Aleejoh13wpepperysalt** [comment]
Thank you @vaisd007302

**Comment by Aleejoh13wpepperysalt** [comment]
I won't let me disconnect my headphone I think it gave me a virus

**Comment by genericexists** [comment]
yeah it's a virus known as "SkiddedCode", delete it immediately

**Comment by TheAmazingAceLeo** [comment]
> yeah it's a virus known as "SkiddedCode", delete it immediately

oh no not SkiddedCode, that's really dangerous!

**Comment by swagging-post** [comment]
> I won't let me disconnect my headphone I think it gave me a virus

no it didn't lol, js bookmarks aren't possible to do that stuff

**Comment by TheAmazingAceLeo** [comment]
guys i tihkn tat ther be viuses ni this
