### ISSUE TITLE
i use this almost every day but i got suspended while using pin guesser it uses so many codes its easy to detect

### ISSUE THREAD

**Issue by DARKTONIKXXXYT** [swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI#80]

**Comment by 0alter0** [comment]
sorry bro, but he cant fix anything cuz he don't know anything about blooket coding. Because it aint his

**Comment by vaisd007302** [comment]
How is he merging multiple people's code together to make his cheats better if he doesn't know anything about Blooket coding?

**Comment by DARKTONIKXXXYT** [comment]
he know how it his from what i know this is the only working gui ive found so just do use pin guesser

**Comment by swagging-post** [comment]
it works lol, we got haters photoshopping my original stuff. fixing the anticheat later

**Comment by 0alter0** [comment]
This isn't his, you guys just never looked. Literally, one of the first results is of 05konz'.
