### ISSUE TITLE
DONT TRUST THIS SKID

### ISSUE THREAD

**Issue by 0alter0** [swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI#81]
This (s)kid is just stealing 05konz', Minesraft2's, etc and saying it's his own, it's not. Do NOT trust this kid. To the skid who has this up, just delete it, it's not yours and there is no proof of it being yours. He hasn't made a SINGLE thing on this. Not one cheat is original, all copied, do not use this, go to https://github.com/randomstuff69/blooketpluscheats/blob/main/GUI/Gui.min.js or https://gitlab.com/blooket/blooket-cheats/-/tree/main . These are the REAL creators.

**Comment by 0alter0** [comment]
Also 05konz isn't gone, you can look up blooket cheats, scroll down, and find his GITLAB page.

**Comment by vaisd007302** [comment]
He's just mixing them together to make them better. He gave credit in the [README.md (https://github.com/swagging-post/Blooket-Cheat-GUI-aka-Swaggers-GUI/blob/main/README.md). He never said it was all his.

**Comment by 0alter0** [comment]
he didnt bring shit brother. None of this work is his. Also mixing, tf you mean mixing?? Literally blooket cheats plus

**Comment by 0alter0** [comment]
![image](https://github.com/user-attachments/assets/7cb94306-d58f-43ea-9334-565f05ad8c1f)

**Comment by TheAmazingAceLeo** [comment]
yh look at this 
![Uploading image.png…]()

**Comment by TheAmazingAceLeo** [comment]
![image](https://github.com/user-attachments/assets/fae1df26-0c8d-4aae-b2ba-70a2cfeb7cb8)

**Comment by 0alter0** [comment]
wild how yall think this man really did somethin too

**Comment by TheAmazingAceLeo** [comment]
commits never lie 
![image](https://github.com/user-attachments/assets/7e4491dc-de89-4dd7-866e-5b9bb1f67c49)

**Comment by swagging-post** [comment]
idiots, nice Photoshop 😂
